### ISSUE TITLE
Roadmap v1

### ISSUE THREAD

**Issue by BB9z** [RFUI/RFMessageManager#1]
Should totally redesign.

- [ ] Concurrent queue
- [x] Cover message object to a protocol
- [x] Message has a string type
- [ ] Manager delegate to control message display?
- [ ] Remove RFNetworkActivityIndicatorMessage
